<a href="https://colab.research.google.com/github/Navya40869/edge-idps-colab/blob/main/preprocessing/01_data_prep.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import os

path = "/content/drive/MyDrive/Edge-IDPS-Data/raw_data"
print(os.listdir(path))

['Stratified_data.csv']

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
import os

file_path = "/content/drive/MyDrive/Edge-IDPS-Data/raw_data/Stratified_data.csv"

size_mb = os.path.getsize(file_path) / (1024 * 1024)
print(f"File size: {size_mb:.2f} MB")

File size: 1744.09 MB

In [3]:
import pandas as pd

file_path = "/content/drive/MyDrive/Edge-IDPS-Data/raw_data/Stratified_data.csv"

# Load only the first 100,000 rows
df = pd.read_csv(file_path, nrows=100000)

print("Dataset loaded successfully!")
print(df.shape)

Dataset loaded successfully!
(100000, 40)

In [4]:
df.head()

,Header_Length,Protocol Type,Time_To_Live,Rate,fin_flag_number,syn_flag_number,rst_flag_number,psh_flag_number,ack_flag_number,ece_flag_number,...,Tot sum,Min,Max,AVG,Std,Tot size,IAT,Number,Variance,Label
0,32.0,6,99.4,10041.426861,0.0,0.0,0.0,0.5,1.0,0.0,...,16016.0,66.0,4254.0,1601.6,1536.304889,1601.6,0.000103,10.0,2.360233e+06,BENIGN
1,32.0,6,120.0,641.311275,0.0,0.0,0.0,0.2,1.0,0.0,...,9794.0,66.0,2962.0,979.4,974.595437,979.4,0.002116,10.0,9.498363e+05,BENIGN
2,29.6,6,77.2,62.990968,0.0,0.0,0.0,0.3,0.9,0.0,...,5965.0,66.0,2962.0,596.5,947.314948,596.5,0.022838,10.0,8.974056e+05,BENIGN
3,25.2,6,80.9,410.273104,0.0,0.0,0.0,0.1,0.8,0.0,...,12395.0,60.0,2962.0,1239.5,920.812835,1239.5,0.003697,10.0,8.478963e+05,BENIGN
4,32.0,6,130.8,2895.019326,0.0,0.0,0.0,0.0,1.0,0.0,...,9348.0,66.0,1514.0,934.8,747.743985,934.8,0.000378,10.0,5.591211e+05,BENIGN

In [5]:
print("Rows and Columns:", df.shape)

Rows and Columns: (100000, 40)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 40 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   Header_Length    100000 non-null  float64
 1   Protocol Type    100000 non-null  int64
 2   Time_To_Live     100000 non-null  float64
 3   Rate             100000 non-null  float64
 4   fin_flag_number  100000 non-null  float64
 5   syn_flag_number  100000 non-null  float64
 6   rst_flag_number  100000 non-null  float64
 7   psh_flag_number  100000 non-null  float64
 8   ack_flag_number  100000 non-null  float64
 9   ece_flag_number  100000 non-null  float64
 10  cwr_flag_number  100000 non-null  float64
 11  ack_count        100000 non-null  float64
 12  syn_count        100000 non-null  float64
 13  fin_count        100000 non-null  float64
 14  rst_count        100000 non-null  float64
 15  HTTP             100000 non-null  float64
 16  HTTPS            100000 non-null  float64
 17  DNS              100000 non-null  float64
 18  Telnet           100000 non-null  float64
 19  SMTP             100000 non-null  float64
 20  SSH              100000 non-null  float64
 21  IRC              100000 non-null  float64
 22  TCP              100000 non-null  float64
 23  UDP              100000 non-null  float64
 24  DHCP             100000 non-null  float64
 25  ARP              100000 non-null  float64
 26  ICMP             100000 non-null  float64
 27  IGMP             100000 non-null  float64
 28  IPv              100000 non-null  float64
 29  LLC              100000 non-null  float64
 30  Tot sum          100000 non-null  float64
 31  Min              100000 non-null  float64
 32  Max              100000 non-null  float64
 33  AVG              100000 non-null  float64
 34  Std              100000 non-null  float64
 35  Tot size         100000 non-null  float64
 36  IAT              100000 non-null  float64
 37  Number           100000 non-null  float64
 38  Variance         100000 non-null  float64
 39  Label            100000 non-null  object
dtypes: float64(38), int64(1), object(1)
memory usage: 30.5+ MB

In [7]:
df.isnull().sum()

Header_Length      0
Protocol Type      0
Time_To_Live       0
Rate               0
fin_flag_number    0
syn_flag_number    0
rst_flag_number    0
psh_flag_number    0
ack_flag_number    0
ece_flag_number    0
cwr_flag_number    0
ack_count          0
syn_count          0
fin_count          0
rst_count          0
HTTP               0
HTTPS              0
DNS                0
Telnet             0
SMTP               0
SSH                0
IRC                0
TCP                0
UDP                0
DHCP               0
ARP                0
ICMP               0
IGMP               0
IPv                0
LLC                0
Tot sum            0
Min                0
Max                0
AVG                0
Std                0
Tot size           0
IAT                0
Number             0
Variance           0
Label              0
dtype: int64

In [8]:
print(df.columns.tolist())

['Header_Length', 'Protocol Type', 'Time_To_Live', 'Rate', 'fin_flag_number', 'syn_flag_number', 'rst_flag_number', 'psh_flag_number', 'ack_flag_number', 'ece_flag_number', 'cwr_flag_number', 'ack_count', 'syn_count', 'fin_count', 'rst_count', 'HTTP', 'HTTPS', 'DNS', 'Telnet', 'SMTP', 'SSH', 'IRC', 'TCP', 'UDP', 'DHCP', 'ARP', 'ICMP', 'IGMP', 'IPv', 'LLC', 'Tot sum', 'Min', 'Max', 'AVG', 'Std', 'Tot size', 'IAT', 'Number', 'Variance', 'Label']

In [10]:
df['Label'].value_counts()

Label
DDOS-ICMP_FLOOD            22020
DDOS-TCP_FLOOD             13698
DDOS-PSHACK_FLOOD          12512
DDOS-SYN_FLOOD             12395
DDOS-RSTFINFLOOD           12312
DDOS-SYNONYMOUSIP_FLOOD    10975
DDOS-UDP_FLOOD              9485
BENIGN                      3319
DDOS-ICMP_FRAGMENTATION     1423
DDOS-ACK_FRAGMENTATION       880
DOS-UDP_FLOOD                208
DOS-TCP_FLOOD                161
DOS-SYN_FLOOD                132
DDOS-HTTP_FLOOD               81
DDOS-SLOWLORIS                70
MIRAI-GREETH_FLOOD            70
MIRAI-UDPPLAIN                60
MIRAI-GREIP_FLOOD             47
VULNERABILITYSCAN             27
MITM-ARPSPOOFING              22
BROWSERHIJACKING              18
DDOS-UDP_FRAGMENTATION        18
COMMANDINJECTION              15
DNS_SPOOFING                  11
RECON-HOSTDISCOVERY           10
BACKDOOR_MALWARE              10
RECON-OSSCAN                   8
RECON-PORTSCAN                 7
DOS-HTTP_FLOOD                 5
DICTIONARYBRUTEFORCE           1
Name: count, dtype: int64

In [11]:
print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 10576

In [12]:
df.describe()

,Header_Length,Protocol Type,Time_To_Live,Rate,fin_flag_number,syn_flag_number,rst_flag_number,psh_flag_number,ack_flag_number,ece_flag_number,...,LLC,Tot sum,Min,Max,AVG,Std,Tot size,IAT,Number,Variance
count,100000.000000,100000.000000,100000.000000,1.000000e+05,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,...,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,1.000000e+05,100000.000000,1.000000e+05
mean,14.335818,5.990910,65.961698,inf,0.123238,0.234128,0.128309,0.127260,0.157969,0.000012,...,0.997954,8158.805970,64.712610,183.723590,101.038131,37.305467,101.038131,4.494062e-04,96.853700,3.675070e+04
std,8.920981,4.478512,13.258294,NaN,0.327216,0.420476,0.328869,0.322369,0.349724,0.001029,...,0.013916,12938.277297,63.954534,594.898886,204.613488,188.040831,204.613488,1.723708e-02,16.501533,4.404883e+05
min,0.000000,0.000000,23.340000,1.853842e-01,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.330000,120.000000,42.000000,60.000000,59.060000,0.000000,59.060000,4.768372e-07,2.000000,0.000000e+00
25%,8.000000,6.000000,64.000000,1.502419e+04,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,1.000000,6000.000000,60.000000,60.000000,60.000000,0.000000,60.000000,2.420902e-05,100.000000,0.000000e+00
50%,20.000000,6.000000,64.000000,2.835330e+04,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,1.000000,6000.000000,60.000000,60.000000,60.000000,0.000000,60.000000,3.572941e-05,100.000000,0.000000e+00
75%,20.000000,6.000000,64.000000,4.182593e+04,0.000000,0.010000,0.000000,0.000000,0.010000,0.000000,...,1.000000,6000.000000,60.000000,60.000000,60.000000,0.000000,60.000000,6.721020e-05,100.000000,0.000000e+00
max,60.000000,47.000000,247.000000,inf,1.000000,1.000000,1.000000,1.000000,1.000000,0.200000,...,1.000000,234209.000000,1514.000000,21786.000000,4324.700000,6455.713749,4324.700000,5.394203e+00,100.000000,4.167624e+07

In [13]:
df = df.drop_duplicates()

print("New dataset shape:", df.shape)
print("Duplicate rows:", df.duplicated().sum())

New dataset shape: (89424, 40)
Duplicate rows: 0

In [14]:
# Features
X = df.drop("Label", axis=1)

# Target
y = df["Label"]

print("Features shape:", X.shape)
print("Labels shape:", y.shape)

Features shape: (89424, 39)
Labels shape: (89424,)

In [15]:
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()

y = label_encoder.fit_transform(y)

print("Number of classes:", len(label_encoder.classes_))
print(label_encoder.classes_)

Number of classes: 30
['BACKDOOR_MALWARE' 'BENIGN' 'BROWSERHIJACKING' 'COMMANDINJECTION'
 'DDOS-ACK_FRAGMENTATION' 'DDOS-HTTP_FLOOD' 'DDOS-ICMP_FLOOD'
 'DDOS-ICMP_FRAGMENTATION' 'DDOS-PSHACK_FLOOD' 'DDOS-RSTFINFLOOD'
 'DDOS-SLOWLORIS' 'DDOS-SYNONYMOUSIP_FLOOD' 'DDOS-SYN_FLOOD'
 'DDOS-TCP_FLOOD' 'DDOS-UDP_FLOOD' 'DDOS-UDP_FRAGMENTATION'
 'DICTIONARYBRUTEFORCE' 'DNS_SPOOFING' 'DOS-HTTP_FLOOD' 'DOS-SYN_FLOOD'
 'DOS-TCP_FLOOD' 'DOS-UDP_FLOOD' 'MIRAI-GREETH_FLOOD' 'MIRAI-GREIP_FLOOD'
 'MIRAI-UDPPLAIN' 'MITM-ARPSPOOFING' 'RECON-HOSTDISCOVERY' 'RECON-OSSCAN'
 'RECON-PORTSCAN' 'VULNERABILITYSCAN']

In [17]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X = scaler.fit_transform(X)

print("Feature scaling completed!")

ValueError: Input X contains infinity or a value too large for dtype('float64').

In [18]:
import numpy as np

# Count infinite values
print("Number of infinite values:", np.isinf(X).sum().sum())

Number of infinite values: 1

In [20]:
X = X.replace([np.inf, -np.inf], np.nan)

In [21]:
print(X.isnull().sum())

Header_Length      0
Protocol Type      0
Time_To_Live       0
Rate               1
fin_flag_number    0
syn_flag_number    0
rst_flag_number    0
psh_flag_number    0
ack_flag_number    0
ece_flag_number    0
cwr_flag_number    0
ack_count          0
syn_count          0
fin_count          0
rst_count          0
HTTP               0
HTTPS              0
DNS                0
Telnet             0
SMTP               0
SSH                0
IRC                0
TCP                0
UDP                0
DHCP               0
ARP                0
ICMP               0
IGMP               0
IPv                0
LLC                0
Tot sum            0
Min                0
Max                0
AVG                0
Std                0
Tot size           0
IAT                0
Number             0
Variance           0
dtype: int64

In [22]:
X = X.fillna(X.median())

In [23]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X = scaler.fit_transform(X)

print("Feature scaling completed!")

Feature scaling completed!

In [24]:
import numpy as np

X = X.replace([np.inf, -np.inf], np.nan)

AttributeError: 'numpy.ndarray' object has no attribute 'replace'

In [26]:
X = df.drop("Label", axis=1)

In [27]:
import numpy as np

X = X.replace([np.inf, -np.inf], np.nan)
X = X.fillna(X.median())

In [28]:
print("Infinite values:", np.isinf(X).sum().sum())
print("Missing values:", X.isnull().sum().sum())

Infinite values: 0
Missing values: 0

In [29]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X = scaler.fit_transform(X)

print("Feature scaling completed!")

Feature scaling completed!

In [30]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("Training set:", X_train.shape)
print("Testing set:", X_test.shape)

ValueError: The least populated class in y has only 1 member, which is too few. The minimum number of groups for any class cannot be less than 2.

In [31]:
import pandas as pd

# Convert encoded labels back to a Series if needed
y_series = pd.Series(y)

print(y_series.value_counts().sort_values())

16        1
18        5
28        7
27        8
26       10
0        10
17       11
3        15
2        18
15       18
25       22
29       27
23       47
24       60
22       70
10       70
5        81
19      132
20      161
21      208
4       880
7      1423
1      3319
14     8807
11     9954
9     11023
12    11372
8     11508
13    11938
6     18219
Name: count, dtype: int64

In [32]:
print(df["Label"].value_counts().sort_values())

Label
DICTIONARYBRUTEFORCE           1
DOS-HTTP_FLOOD                 5
RECON-PORTSCAN                 7
RECON-OSSCAN                   8
RECON-HOSTDISCOVERY           10
BACKDOOR_MALWARE              10
DNS_SPOOFING                  11
COMMANDINJECTION              15
BROWSERHIJACKING              18
DDOS-UDP_FRAGMENTATION        18
MITM-ARPSPOOFING              22
VULNERABILITYSCAN             27
MIRAI-GREIP_FLOOD             47
MIRAI-UDPPLAIN                60
MIRAI-GREETH_FLOOD            70
DDOS-SLOWLORIS                70
DDOS-HTTP_FLOOD               81
DOS-SYN_FLOOD                132
DOS-TCP_FLOOD                161
DOS-UDP_FLOOD                208
DDOS-ACK_FRAGMENTATION       880
DDOS-ICMP_FRAGMENTATION     1423
BENIGN                      3319
DDOS-UDP_FLOOD              8807
DDOS-SYNONYMOUSIP_FLOOD     9954
DDOS-RSTFINFLOOD           11023
DDOS-SYN_FLOOD             11372
DDOS-PSHACK_FLOOD          11508
DDOS-TCP_FLOOD             11938
DDOS-ICMP_FLOOD            18219
Name: count, dtype: int64

In [33]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print("Training set:", X_train.shape)
print("Testing set:", X_test.shape)

Training set: (71539, 39)
Testing set: (17885, 39)

In [34]:
print(df["Label"].value_counts().sort_values().head(10))

Label
DICTIONARYBRUTEFORCE       1
DOS-HTTP_FLOOD             5
RECON-PORTSCAN             7
RECON-OSSCAN               8
RECON-HOSTDISCOVERY       10
BACKDOOR_MALWARE          10
DNS_SPOOFING              11
COMMANDINJECTION          15
BROWSERHIJACKING          18
DDOS-UDP_FRAGMENTATION    18
Name: count, dtype: int64

In [35]:
import joblib

joblib.dump(scaler, "/content/drive/MyDrive/Edge-IDPS-Data/scaler.pkl")
joblib.dump(label_encoder, "/content/drive/MyDrive/Edge-IDPS-Data/label_encoder.pkl")

print("Scaler and Label Encoder saved!")

Scaler and Label Encoder saved!

In [36]:
joblib.dump(X_train, "/content/drive/MyDrive/Edge-IDPS-Data/X_train.pkl")
joblib.dump(X_test, "/content/drive/MyDrive/Edge-IDPS-Data/X_test.pkl")
joblib.dump(y_train, "/content/drive/MyDrive/Edge-IDPS-Data/y_train.pkl")
joblib.dump(y_test, "/content/drive/MyDrive/Edge-IDPS-Data/y_test.pkl")

print("Training and testing datasets saved!")

Training and testing datasets saved!

In [37]:
counts = df["Label"].value_counts()

valid_labels = counts[counts >= 2].index

df = df[df["Label"].isin(valid_labels)]

print(df["Label"].value_counts().sort_values().head())

Label
DOS-HTTP_FLOOD          5
RECON-PORTSCAN          7
RECON-OSSCAN            8
BACKDOOR_MALWARE       10
RECON-HOSTDISCOVERY    10
Name: count, dtype: int64

In [38]:
df.to_csv(
    "/content/drive/MyDrive/Edge-IDPS-Data/preprocessed_data.csv",
    index=False
)

print("Preprocessed dataset saved!")

Preprocessed dataset saved!

In [39]:
df = df.drop_duplicates()

In [40]:
# Option A: Group rare attack labels into an "Other" or broader category
value_counts = df['Label'].value_counts()
rare_classes = value_counts[value_counts < 10].index
df['Label'] = df['Label'].replace(rare_classes, 'Other_Attacks')

# Now stratify=y will work seamlessly!
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

ValueError: The least populated class in y has only 1 member, which is too few. The minimum number of groups for any class cannot be less than 2.

In [41]:
# 1. Count how many times each class appears
class_counts = y.value_counts()

# 2. Identify classes that appear fewer than 2 times (or fewer than 5)
rare_classes = class_counts[class_counts < 2].index

# 3. Filter out those single-sample rows from both X and y
valid_indices = ~y.isin(rare_classes)
X_clean = X[valid_indices]
y_clean = y[valid_indices]

# 4. Now run train_test_split on the cleaned data
X_train, X_test, y_train, y_test = train_test_split(
    X_clean, y_clean, test_size=0.2, random_state=42, stratify=y_clean
)

print("Split completed successfully!")
print("Training shape:", X_train.shape)
print("Testing shape:", X_test.shape)

AttributeError: 'numpy.ndarray' object has no attribute 'value_counts'

In [42]:
import numpy as np
from sklearn.model_selection import train_test_split

# 1. Get unique classes and their counts in the NumPy array y
classes, counts = np.unique(y, return_counts=True)

# 2. Identify classes that appear fewer than 2 times
rare_classes = classes[counts < 2]

# 3. Create a boolean mask to filter out single-sample classes from X and y
mask = ~np.isin(y, rare_classes)
X_clean = X[mask]
y_clean = y[mask]

# 4. Now run train_test_split on the cleaned arrays
X_train, X_test, y_train, y_test = train_test_split(
    X_clean, y_clean, test_size=0.2, random_state=42, stratify=y_clean
)

print("Split completed successfully!")
print("Training shape:", X_train.shape)
print("Testing shape:", X_test.shape)

Split completed successfully!
Training shape: (71538, 39)
Testing shape: (17885, 39)

In [43]:
import joblib
import numpy as np

# Set your shared Google Drive directory path
save_path = "/content/drive/MyDrive/Edge-IDPS-Data/processed_data/"

# 1. Save the Scaler (CRUCIAL for Member 3's Streaming Pipeline)
joblib.dump(scaler, save_path + "scaler.pkl")

# 2. Save the Cleaned Splits (For Member 2's AI Model GPU Training)
np.save(save_path + "X_train.npy", X_train)
np.save(save_path + "y_train.npy", y_train)
np.save(save_path + "X_test.npy", X_test)
np.save(save_path + "y_test.npy", y_test)

print("All preprocessed artifacts saved successfully to Google Drive!")

FileNotFoundError: [Errno 2] No such file or directory: '/content/drive/MyDrive/Edge-IDPS-Data/processed_data/scaler.pkl'

In [44]:
import os
import joblib
import numpy as np

# Set your target directory path
save_path = "/content/drive/MyDrive/Edge-IDPS-Data/processed_data/"

# Create the folder automatically if it doesn't exist
os.makedirs(save_path, exist_ok=True)

# 1. Save the Scaler
joblib.dump(scaler, save_path + "scaler.pkl")

# 2. Save the Cleaned Splits
np.save(save_path + "X_train.npy", X_train)
np.save(save_path + "y_train.npy", y_train)
np.save(save_path + "X_test.npy", X_test)
np.save(save_path + "y_test.npy", y_test)

print("All preprocessed artifacts saved successfully to Google Drive!")

All preprocessed artifacts saved successfully to Google Drive!